services:
  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_NAME:-redis-db}
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${CONTAINER_NAME:-redis-db}-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD}
    ports:
      - "${REDIS_COMMANDER_PORT:-8080}:8081"
    depends_on:
      - redis
    networks:
      - redis_network

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
