# Railway Deployment Configuration
[build]
builder = "dockerfile"

[build.env]
NODE_ENV = "production"

[deploy]
startCommand = "npm start"

[env]
SUPABASE_URL = "${{SUPABASE_URL}}"
SUPABASE_KEY = "${{SUPABASE_KEY}}"
SUPABASE_SERVICE_ROLE_KEY = "${{SUPABASE_SERVICE_ROLE_KEY}}"
