# Railway Deployment Configuration
[build]
context = "./backend"

[build.env]
NODE_ENV = "production"

[deploy]
startCommand = "node server.js"

[env]
SUPABASE_URL = "${{SUPABASE_URL}}"
SUPABASE_KEY = "${{SUPABASE_KEY}}"
SUPABASE_SERVICE_ROLE_KEY = "${{SUPABASE_SERVICE_ROLE_KEY}}"
