services:
  mysql:
    image: mysql:5.7
    container_name: test-wp-mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspass123
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    volumes:
      - test-wp-mysql-data:/var/lib/mysql
    networks:
      - test-wp-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp

  wordpress:
    image: wordpress:latest
    container_name: test-wp-wordpress
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: test-wp-mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass123
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://localhost:8080');
        define('WP_SITEURL','http://localhost:8080');
    volumes:
      - test-wp-wp-data:/var/www/html
    depends_on:
      - mysql
    networks:
      - test-wp-network
    restart: unless-stopped

volumes:
  test-wp-wp-data:
  test-wp-mysql-data:

networks:
  test-wp-network:
    driver: bridge
