version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql
    ports:
      - "${PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${APP_NAME}-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ${APP_NAME}-network

volumes:
  ${APP_NAME}-mysql-data:

networks:
  ${APP_NAME}-network:
    driver: bridge
