services:
  mysql:
    image: mysql:5.7
    container_name: miwp-yago-mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspass
    volumes:
      - miwp-yago-mysql-data:/var/lib/mysql
    networks:
      - miwp-yago-network
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: miwp-yago-wordpress
    platform: linux/amd64
    ports:
      - "8210:80"
    environment:
      WORDPRESS_DB_HOST: miwp-yago-mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - miwp-yago-wp-data:/var/www/html
    depends_on:
      - mysql
    networks:
      - miwp-yago-network
    restart: unless-stopped

volumes:
  miwp-yago-wp-data:
  miwp-yago-mysql-data:

networks:
  miwp-yago-network:
    driver: bridge
