name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd backend && npm ci

    - name: Build project
      run: |
        npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          cd /var/www/xistracloud || cd ~/xistracloud

          # Backup current version
          sudo cp -r . ../xistracloud-backup-$(date +%Y%m%d-%H%M%S) || true

          # Pull latest changes
          git pull origin main

          # Install dependencies
          npm install --production
          cd backend && npm install --production && cd ..

          # Build frontend
          npm run build

          # Restart services
          sudo systemctl restart xistracloud-backend || pm2 restart xistracloud-backend || true
          sudo systemctl restart nginx || service nginx reload || true

          echo "✅ Deploy completed successfully"